name: Python Ci
on: [push]
jobs:
    python-check:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up python
              uses: actions/setup-python@v4
              with:
                python-version: '3.11'  
            
            - name: Install dependencies
              run: |
                python -m pip install -r requirements.txt
            - name: Pytest
              run: |
                pytest
    docker-build:
        runs-on: ubuntu-latest
        needs: python-check
        
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            
            - name: Docker build
              run: |
                docker build -t heello-devops .
                docker run --rm heello-devops python -c "from main import app; print('Flask app imported successfully in Docker!')"

